### ISSUE TITLE
Cannot install swanky-webpack

### ISSUE THREAD

**Issue by uglow** [swanky-docs/swanky-webpack#1]
## Issue

When running `npm i swanky-webpack`, an installation error occurs:
```
$ npm i swanky-webpack
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/brett/.nvm/versions/node/v6.2.2/bin/node" "/Users/brett/.nvm/versions/node/v6.2.2/bin/npm" "i" "swanky-webpack"
npm ERR! node v6.2.2
npm ERR! npm  v4.0.2
npm ERR! path /mydev/code/yo/test/node_modules/swanky-webpack/node_modules/webpack/bin/webpack.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/mydev/code/yo/test/node_modules/swanky-webpack/node_modules/webpack/bin/webpack.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/mydev/code/yo/test/node_modules/swanky-webpack/node_modules/webpack/bin/webpack.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /mydev/code/yo/test/npm-debug.log
```

No `node_modules/swanky-webpack` directory is created. The same thing occurs when installing `swanky-server` (2.11.0).

## Workaround
None?

## Environment
Node 6.2.2
NPM 4.0

**Comment by rodleviton** [comment]
I have mirrored your Node and NPM versions and have run an install of `swanky-webpack`. The installation completes successfully and a `swanky-webpack` folder is created within the `node_modules` folder. I have also successfully run the docs site locally. Do you have a branch that I can pull down and run locally? also note you should be using `swanky-server` 2.11.1.

**Comment by rodleviton** [comment]
Ok got it! If the projects webpack version matches the swanky-webpack version it pull the dependency to the root level of the node_modules folder,

e.g.

Following will cause error as webpack versions are shared

```
  "devDependencies": {
    "swanky-server": "2.9.0",
    "swanky-webpack": "^1.0.1", // webpack v2.1.0-beta.27
    "webpack": "v2.1.0-beta.27"
  }
```

Following will not cause error as webpack versions are different

```
  "devDependencies": {
    "swanky-server": "2.9.0",
    "swanky-webpack": "^1.0.1", // webpack v2.1.0-beta.27
    "webpack": "v2.1.0-beta.25"
  }
```

Will need to investigate how to avoid this issue.

**Comment by rodleviton** [comment]
@uglow `npm shrinkwrap` seems to be a fairly robust solution to the problem. By 'shrinkwrapping' `swanky-webpack` dependencies the exact dependency structure is recreated within the `swanky-webpack` node_modules folder. This way I can guarantee that the `.bin` file location will always be the same regardless of shared dependencies and npm versions. Please update to `swanky-webpack v1.0.2` and `swanky-server v2.11.2` and let me know how you go.

Please note you can know use the swanky-webpack binary to build the docs and be guaranteed it will be using the webpack binary version specified by swanky.

```
    "docs:build": "cross-env NODE_ENV=production swanky-webpack -p --progress --config config/docs/swanky.webpack.config.js --colors",
```

**Comment by uglow** [comment]
Thanks @rodleviton - I'll check it tomorrow morning. We are learning a lot about Node through this process 👍

**Comment by rodleviton** [comment]
Indeed @uglow - I didnt even know what `npm shrinkwrap` was before today.

**Comment by uglow** [comment]
So by shrink-wrapping swanky-webpack, it ensures there is a "private" webpack for swanky-server to use. However any modules which refer to `require('webpack/...')` start to break. E.g. the ExtractTextPlugin refers to `webpack/lib/removeAndDo`, which is not in `/node_modules/webpack` (that directory does not exist), but is in `/node_modules/swanky-webpack/node_modules/webpack`.

I think the best workaround for Confit right now is to make webpack a first-class dev dependency for any project (browser OR Node) that wants to generate documentation (using Swanky).

A better solution would be for the webpack/lib code to live in it's own module, and ExtractTextPlugin requires that module directly. @sokra, is that on the cards?
